xcodeproj 'AeroGear-Crypto-Demo.xcodeproj'
platform :ios, '5.0'
         
pod 'AeroGear', { :git => 'https://github.com/cvasilak/aerogear-ios', :branch => 'key-service.AGIOS-83' }
pod 'AeroGear-Crypto', { :git => 'https://github.com/aerogear/aerogear-crypto-ios.git', :branch => 'master' }
pod 'UIActionSheet-Blocks'
pod 'UIAlertView+Blocks'
pod 'SVProgressHUD'
